### ISSUE TITLE
Consider ensuring end-to-end configuration authenticity

### ISSUE THREAD

**Issue by sysrqb** [chris-wood/draft-group-privacypass-consistency-mirror#10]
The client may not have a mechanism for verifying that a configuration is authentic - only consistent within the assumptions of the design. For Privacy Pass, the client already processes a cryptographic key from which it derives the keyid and the client trusts that its set of K-Check mirrors won't collude with the origin. A similar situation exists with other profiles, such as OHTTP.

One suggestion we received is requiring self-authenticating configurations.

**Comment by bemasc** [comment]
Specifically, K-Check appears to weaken the security of OHTTP.  Normally, OHTTP guarantees authenticity and privacy as long as at least one of the proxy or the gateway is well-behaved.  With K-Check, authenticity and privacy can fail even if the gateway is well-behaved, if the K-Check mirrors collude to impersonate the gateway.

**Comment by sysrqb** [comment]
I think there is an unstated assumption somewhere in here. Can you help clarify?

I agree with the privacy and authenticity guarantees you described, without using K-Check, as long as the relay and gateway don't collude and at least one of them is well-behaved. The underlying assumption here is that the client was pre-configured with the gateway's key configuration and that configuration was consistent with all other clients of this service (eliding the need for K-Check, in this case).

In the case where the client must check the consistency of the configuration it has, then we can still assume the client was pre-configured with that configuration. If the client has multiple K-Check servers configured, then if a majority of those servers collude, then they can persuade the client that the pre-configured configuration is not consistent. This would cause a DoS, but not reduce the guarantees of the service.

Were you thinking of different assumptions? Maybe the client isn't pre-configured with the key configuration and it must fetch (or update) its cache?

**Comment by bemasc** [comment]
OK, thanks for the explanation.  For this issue, I think it would be sufficient to clarify that in the document.

As noted in #16, I'm not sure it's always a good idea to draw a total abstraction boundary between correctness and consistency.  If the correctness validation procedure (or subsequent use) relies on a privacy proxy, then the K-Check procedure can safely be simplified to K=1, with improved privacy.

**Comment by bemasc** [comment]
I'm totally OK with defining K-Check (or perhaps the Mirror Protocol) as a limited-purpose component that is separate from authentication and usage of the resource.  Currently, the draft is not clear on that point; I came away with the impression that K-Check was also being used for authentication (which it does provide under certain, slightly worrying security assumptions).

I do think that usage of K-Check is actually not as independent from the protocol as the current text implies, but that's a topic for a different issue.

**Comment by chris-wood** [comment]
@sysrqb do we want to keep this open? I think self-certifying configurations are somewhat orthogonal to the core work here.

**Comment by chris-wood** [comment]
I'm going to close this as resolved, since resources can be self-certifying on top of the mirror protocol without requiring any changes. Please feel free to re-open as needed.
