### ISSUE TITLE
Rely on a quorum of mirrors

### ISSUE THREAD

**Issue by sysrqb** [chris-wood/draft-group-privacypass-consistency-mirror#11]
Currently we describe the failure mode based on some probability of mirror failure/misbehavior. This can be improved.

```
With at least one dishonest mirror, the probability of discovering an inconsistency is 1 - (1 / 2^(k-1)). This is the probability that each individual mirror check succeeds in the mirror protocol.
```

One suggestion we received is using a concept of quorum instead.

**Comment by chris-wood** [comment]
I think we can safely close this now.
